export const keys = {
  GET_MY_PROFILE: "/members/profile",
  GET_WEEKLY_MOST_VIEWED_BOOKS: "/books/weekly-most-viewed",
  GET_BOOKS: "/books",
  GET_BOOK: "/books/info",
  GET_BOOK_COMMENTS: "/books/comments",
  GET_BOOK_LIKED: "/members/books/liked",
  GET_MY_BOOKS: "/studio/dashboard",
  GET_MY_BOOK: "/studio/dashboard/books",
  GET_FLOW_CHART: "/studio/books/flow-chart",
  GET_DASHBOARD_INTRO_PAGE: "/studio/books/pages/intro",
  GET_DASHBOARD_PAGE: "/studio/books/pages",
  GET_INTRO_PAGE: "/books/pages/intro",
  GET_PAGE: "/books/pages",
  GET_BOARD_THREADS: "/boards/threads",
  GET_BOARD_THREAD: "/boards/thread",
  GET_BOARD_FIXED_THREADS: "/boards/threads/fixed",
  GET_BOARD_THREAD_COMMENTS: "/boards/threads/comments",
  GET_NEW_USERS_STATISTICS: "/admin/statistics/new-users",
  GET_NEW_BOOKS_STATISTICS: "/admin/statistics/new-books",
};
